
insert into car (id, make, model) values (1, 'Pontiac', 'Sunbird');
insert into car (id, make, model) values (2, 'Subaru', 'Tribeca');
insert into car (id, make, model) values (3, 'Buick', 'Rendezvous');
insert into car (id, make, model) values (4, 'Infiniti', 'EX');
insert into car (id, make, model) values (5, 'Chevrolet', 'Impala');
insert into car (id, make, model) values (6, 'Chevrolet', 'Express 3500');
insert into car (id, make, model) values (7, 'Pontiac', '1000');
insert into car (id, make, model) values (8, 'Volkswagen', 'Type 2');
insert into car (id, make, model) values (9, 'Toyota', 'Tacoma');
insert into car (id, make, model) values (10, 'GMC', 'Sonoma');
insert into car (id, make, model) values (11, 'GMC', 'Yukon');
insert into car (id, make, model) values (12, 'Plymouth', 'Neon');
insert into car (id, make, model) values (13, 'Chevrolet', 'Prizm');
insert into car (id, make, model) values (14, 'Acura', 'TL');
insert into car (id, make, model) values (15, 'GMC', 'Rally Wagon 3500');
insert into car (id, make, model) values (16, 'BMW', '5 Series');
insert into car (id, make, model) values (17, 'Subaru', 'Outback');
insert into car (id, make, model) values (18, 'Honda', 'CR-V');
insert into car (id, make, model) values (19, 'Dodge', 'Durango');
insert into car (id, make, model) values (20, 'Subaru', 'Legacy');
insert into car (id, make, model) values (21, 'Pontiac', 'Grand Am');
insert into car (id, make, model) values (22, 'Jaguar', 'X-Type');
insert into car (id, make, model) values (23, 'Bentley', 'Arnage');
insert into car (id, make, model) values (24, 'Mitsubishi', 'GTO');
insert into car (id, make, model) values (25, 'Lincoln', 'MKZ');
insert into car (id, make, model) values (26, 'Suzuki', 'Grand Vitara');
insert into car (id, make, model) values (27, 'Volkswagen', 'Golf');
insert into car (id, make, model) values (28, 'Toyota', 'Celica');
insert into car (id, make, model) values (29, 'Hyundai', 'Tiburon');
insert into car (id, make, model) values (30, 'Volkswagen', 'GTI');
insert into car (id, make, model) values (31, 'Mercedes-Benz', 'R-Class');
insert into car (id, make, model) values (32, 'Nissan', 'GT-R');
insert into car (id, make, model) values (33, 'Toyota', 'Echo');
insert into car (id, make, model) values (34, 'GMC', 'Yukon');
insert into car (id, make, model) values (35, 'Saturn', 'L-Series');
insert into car (id, make, model) values (36, 'Lincoln', 'Continental');
insert into car (id, make, model) values (37, 'GMC', 'Yukon');
insert into car (id, make, model) values (38, 'Ford', 'E-Series');
insert into car (id, make, model) values (39, 'Buick', 'Riviera');
insert into car (id, make, model) values (40, 'Dodge', 'D150');
insert into car (id, make, model) values (41, 'Toyota', 'Celica');
insert into car (id, make, model) values (42, 'Mitsubishi', 'Lancer Evolution');
insert into car (id, make, model) values (43, 'Honda', 'Accord');
insert into car (id, make, model) values (44, 'Honda', 'S2000');
insert into car (id, make, model) values (45, 'Saturn', 'S-Series');
insert into car (id, make, model) values (46, 'Volkswagen', 'GTI');
insert into car (id, make, model) values (47, 'GMC', 'Savana 1500');
insert into car (id, make, model) values (48, 'Nissan', 'Rogue');
insert into car (id, make, model) values (49, 'Pontiac', 'Sunfire');
insert into car (id, make, model) values (50, 'Dodge', 'Caravan');
insert into car (id, make, model) values (51, 'Ford', 'Windstar');
insert into car (id, make, model) values (52, 'Dodge', 'Stealth');
insert into car (id, make, model) values (53, 'Land Rover', 'Defender 90');
insert into car (id, make, model) values (54, 'Pontiac', 'Fiero');
insert into car (id, make, model) values (55, 'Acura', 'MDX');
insert into car (id, make, model) values (56, 'Chevrolet', 'Prizm');
insert into car (id, make, model) values (57, 'Toyota', 'Matrix');
insert into car (id, make, model) values (58, 'Kia', 'Sephia');
insert into car (id, make, model) values (59, 'BMW', '5 Series');
insert into car (id, make, model) values (60, 'Audi', '4000s');
insert into car (id, make, model) values (61, 'Honda', 'Odyssey');
insert into car (id, make, model) values (62, 'Dodge', 'Caravan');
insert into car (id, make, model) values (63, 'Mercedes-Benz', 'E-Class');
insert into car (id, make, model) values (64, 'BMW', 'X5 M');
insert into car (id, make, model) values (65, 'Hyundai', 'Veracruz');
insert into car (id, make, model) values (66, 'Volkswagen', 'Type 2');
insert into car (id, make, model) values (67, 'Mitsubishi', 'Truck');
insert into car (id, make, model) values (68, 'Dodge', 'Dakota');
insert into car (id, make, model) values (69, 'Land Rover', 'Freelander');
insert into car (id, make, model) values (70, 'Buick', 'Century');
insert into car (id, make, model) values (71, 'Mercedes-Benz', '300E');
insert into car (id, make, model) values (72, 'Toyota', 'Tacoma');
insert into car (id, make, model) values (73, 'Lamborghini', 'Countach');
insert into car (id, make, model) values (74, 'Toyota', 'Tacoma Xtra');
insert into car (id, make, model) values (75, 'Dodge', 'Magnum');
insert into car (id, make, model) values (76, 'Chevrolet', 'Corvette');
insert into car (id, make, model) values (77, 'Mitsubishi', 'Galant');
insert into car (id, make, model) values (78, 'Volvo', 'C70');
insert into car (id, make, model) values (79, 'Saab', '9000');
insert into car (id, make, model) values (80, 'Mercedes-Benz', 'CL-Class');
insert into car (id, make, model) values (81, 'Ford', 'Focus');
insert into car (id, make, model) values (82, 'Jeep', 'Comanche');
insert into car (id, make, model) values (83, 'Toyota', 'Solara');
insert into car (id, make, model) values (84, 'Acura', 'MDX');
insert into car (id, make, model) values (85, 'Buick', 'Reatta');
insert into car (id, make, model) values (86, 'Mitsubishi', 'Eclipse');
insert into car (id, make, model) values (87, 'Infiniti', 'QX');
insert into car (id, make, model) values (88, 'GMC', 'Jimmy');
insert into car (id, make, model) values (89, 'Saab', '9-5');
insert into car (id, make, model) values (90, 'Pontiac', 'Vibe');
insert into car (id, make, model) values (91, 'Buick', 'Hearse');
insert into car (id, make, model) values (92, 'Toyota', 'Land Cruiser');
insert into car (id, make, model) values (93, 'GMC', 'Sierra 3500');
insert into car (id, make, model) values (94, 'Lincoln', 'Continental');
insert into car (id, make, model) values (95, 'Toyota', 'Paseo');
insert into car (id, make, model) values (96, 'Chrysler', 'Sebring');
insert into car (id, make, model) values (97, 'Chevrolet', 'Caprice');
insert into car (id, make, model) values (98, 'Dodge', 'Ram 2500');
insert into car (id, make, model) values (99, 'Ford', 'F-Series');
insert into car (id, make, model) values (100, 'Lincoln', 'Town Car');
insert into car (id, make, model) values (101, 'GMC', '1500 Club Coupe');
insert into car (id, make, model) values (102, 'Volkswagen', 'Rabbit');
insert into car (id, make, model) values (103, 'BMW', '1 Series');
insert into car (id, make, model) values (104, 'Mazda', 'MPV');
insert into car (id, make, model) values (105, 'Dodge', 'Intrepid');
insert into car (id, make, model) values (106, 'GMC', 'Savana');
insert into car (id, make, model) values (107, 'Chrysler', 'Concorde');
insert into car (id, make, model) values (108, 'Dodge', 'Viper RT/10');
insert into car (id, make, model) values (109, 'Mercury', 'Mystique');
insert into car (id, make, model) values (110, 'Mazda', 'MPV');
insert into car (id, make, model) values (111, 'Infiniti', 'G');
insert into car (id, make, model) values (112, 'Chevrolet', 'Colorado');
insert into car (id, make, model) values (113, 'Nissan', 'GT-R');
insert into car (id, make, model) values (114, 'Honda', 'Accord');
insert into car (id, make, model) values (115, 'Land Rover', 'Defender 90');
insert into car (id, make, model) values (116, 'Buick', 'Riviera');
insert into car (id, make, model) values (117, 'Ferrari', '612 Scaglietti');
insert into car (id, make, model) values (118, 'Mazda', '626');
insert into car (id, make, model) values (119, 'Chevrolet', 'Classic');
insert into car (id, make, model) values (120, 'Volkswagen', 'Passat');
insert into car (id, make, model) values (121, 'Mazda', 'RX-7');
insert into car (id, make, model) values (122, 'Pontiac', 'Gemini');
insert into car (id, make, model) values (123, 'Nissan', 'Murano');
insert into car (id, make, model) values (124, 'Mitsubishi', 'Chariot');
insert into car (id, make, model) values (125, 'Lincoln', 'Town Car');
insert into car (id, make, model) values (126, 'Isuzu', 'i-Series');
insert into car (id, make, model) values (127, 'Subaru', 'SVX');
insert into car (id, make, model) values (128, 'Chrysler', '300M');
insert into car (id, make, model) values (129, 'Lexus', 'IS');
insert into car (id, make, model) values (130, 'Chevrolet', 'Corvette');
insert into car (id, make, model) values (131, 'Honda', 'Element');
insert into car (id, make, model) values (132, 'Chevrolet', 'S10');
insert into car (id, make, model) values (133, 'Chevrolet', 'Corvette');
insert into car (id, make, model) values (134, 'Suzuki', 'Grand Vitara');
insert into car (id, make, model) values (135, 'Toyota', 'Corolla');
insert into car (id, make, model) values (136, 'Hyundai', 'Excel');
insert into car (id, make, model) values (137, 'Dodge', 'Shadow');
insert into car (id, make, model) values (138, 'Volkswagen', 'Jetta');
insert into car (id, make, model) values (139, 'Lincoln', 'Continental');
insert into car (id, make, model) values (140, 'Suzuki', 'Esteem');
insert into car (id, make, model) values (141, 'Ferrari', 'F430');
insert into car (id, make, model) values (142, 'Ford', 'C-MAX Hybrid');
insert into car (id, make, model) values (143, 'Porsche', 'Boxster');
insert into car (id, make, model) values (144, 'Chevrolet', 'Express 3500');
insert into car (id, make, model) values (145, 'BMW', 'X3');
insert into car (id, make, model) values (146, 'Cadillac', 'XLR');
insert into car (id, make, model) values (147, 'Hyundai', 'Sonata');
insert into car (id, make, model) values (148, 'Cadillac', 'Seville');
insert into car (id, make, model) values (149, 'Chevrolet', 'Express 2500');
insert into car (id, make, model) values (150, 'Mercedes-Benz', 'SL-Class');
insert into car (id, make, model) values (151, 'Land Rover', 'Range Rover Sport');
insert into car (id, make, model) values (152, 'Hyundai', 'Tiburon');
insert into car (id, make, model) values (153, 'Chevrolet', 'Silverado 1500');
insert into car (id, make, model) values (154, 'Jensen', 'Interceptor');
insert into car (id, make, model) values (155, 'Toyota', 'Avalon');
insert into car (id, make, model) values (156, 'Honda', 'Element');
insert into car (id, make, model) values (157, 'Saab', '9-7X');
insert into car (id, make, model) values (158, 'Lamborghini', 'Murciélago');
insert into car (id, make, model) values (159, 'Ford', 'Bronco II');
insert into car (id, make, model) values (160, 'Mitsubishi', 'Pajero');
insert into car (id, make, model) values (161, 'Mitsubishi', 'GTO');
insert into car (id, make, model) values (162, 'Infiniti', 'G35');
insert into car (id, make, model) values (163, 'Saturn', 'S-Series');
insert into car (id, make, model) values (164, 'Ford', 'Five Hundred');
insert into car (id, make, model) values (165, 'Oldsmobile', 'Cutlass Cruiser');
insert into car (id, make, model) values (166, 'Mercury', 'Cougar');
insert into car (id, make, model) values (167, 'GMC', 'Sonoma');
insert into car (id, make, model) values (168, 'Chevrolet', 'Suburban 1500');
insert into car (id, make, model) values (169, 'Audi', 'TT');
insert into car (id, make, model) values (170, 'Mercury', 'Mountaineer');
insert into car (id, make, model) values (171, 'Dodge', 'Challenger');
insert into car (id, make, model) values (172, 'Hummer', 'H2');
insert into car (id, make, model) values (173, 'Spyker', 'C8 Double 12 S');
insert into car (id, make, model) values (174, 'Toyota', 'Highlander');
insert into car (id, make, model) values (175, 'Maserati', '430');
insert into car (id, make, model) values (176, 'Dodge', 'Viper');
insert into car (id, make, model) values (177, 'Rolls-Royce', 'Ghost');
insert into car (id, make, model) values (178, 'Hyundai', 'Accent');
insert into car (id, make, model) values (179, 'Jeep', 'Cherokee');
insert into car (id, make, model) values (180, 'Ford', 'Laser');
insert into car (id, make, model) values (181, 'Ford', 'Crown Victoria');
insert into car (id, make, model) values (182, 'Chevrolet', 'Suburban 2500');
insert into car (id, make, model) values (183, 'Mitsubishi', 'Challenger');
insert into car (id, make, model) values (184, 'Oldsmobile', '88');
insert into car (id, make, model) values (185, 'Nissan', 'Xterra');
insert into car (id, make, model) values (186, 'Mercedes-Benz', 'E-Class');
insert into car (id, make, model) values (187, 'Maserati', 'Quattroporte');
insert into car (id, make, model) values (188, 'Toyota', '4Runner');
insert into car (id, make, model) values (189, 'Ford', 'Bronco');
insert into car (id, make, model) values (190, 'BMW', 'Z8');
insert into car (id, make, model) values (191, 'Ford', 'Galaxie');
insert into car (id, make, model) values (192, 'Cadillac', 'Allante');
insert into car (id, make, model) values (193, 'Cadillac', 'Escalade');
insert into car (id, make, model) values (194, 'GMC', '1500');
insert into car (id, make, model) values (195, 'Volkswagen', 'Passat');
insert into car (id, make, model) values (196, 'GMC', 'Sierra 1500');
insert into car (id, make, model) values (197, 'Oldsmobile', 'Achieva');
insert into car (id, make, model) values (198, 'Honda', 'Accord');
insert into car (id, make, model) values (199, 'Mercury', 'Topaz');
insert into car (id, make, model) values (200, 'Oldsmobile', 'Aurora');
insert into car (id, make, model) values (201, 'Ford', 'Explorer Sport');
insert into car (id, make, model) values (202, 'Chevrolet', 'S10 Blazer');
insert into car (id, make, model) values (203, 'Dodge', 'Charger');
insert into car (id, make, model) values (204, 'Chevrolet', 'Cavalier');
insert into car (id, make, model) values (205, 'Subaru', 'SVX');
insert into car (id, make, model) values (206, 'Mercedes-Benz', 'CL-Class');
insert into car (id, make, model) values (207, 'Hyundai', 'Sonata');
insert into car (id, make, model) values (208, 'Pontiac', 'Grand Prix');
insert into car (id, make, model) values (209, 'Toyota', 'Matrix');
insert into car (id, make, model) values (210, 'Audi', 'Q7');
insert into car (id, make, model) values (211, 'Volvo', '960');
insert into car (id, make, model) values (212, 'Ford', 'Escape');
insert into car (id, make, model) values (213, 'Mercury', 'Grand Marquis');
insert into car (id, make, model) values (214, 'Buick', 'LeSabre');
insert into car (id, make, model) values (215, 'Infiniti', 'FX');
insert into car (id, make, model) values (216, 'Hyundai', 'Elantra');
insert into car (id, make, model) values (217, 'Chevrolet', 'Impala');
insert into car (id, make, model) values (218, 'Toyota', 'Celica');
insert into car (id, make, model) values (219, 'Maybach', '57');
insert into car (id, make, model) values (220, 'Land Rover', 'Discovery');
insert into car (id, make, model) values (221, 'BMW', '3 Series');
insert into car (id, make, model) values (222, 'Mitsubishi', 'Galant');
insert into car (id, make, model) values (223, 'Ford', 'Explorer Sport');
insert into car (id, make, model) values (224, 'BMW', '6 Series');
insert into car (id, make, model) values (225, 'Jaguar', 'XK');
insert into car (id, make, model) values (226, 'Toyota', 'Tacoma');
insert into car (id, make, model) values (227, 'Chevrolet', 'Caprice Classic');
insert into car (id, make, model) values (228, 'Mazda', 'Millenia');
insert into car (id, make, model) values (229, 'Jaguar', 'S-Type');
insert into car (id, make, model) values (230, 'Peugeot', '207');
insert into car (id, make, model) values (231, 'Nissan', 'Altima');
insert into car (id, make, model) values (232, 'Aston Martin', 'V8 Vantage');
insert into car (id, make, model) values (233, 'Chrysler', 'Sebring');
insert into car (id, make, model) values (234, 'Chevrolet', 'Silverado 2500');
insert into car (id, make, model) values (235, 'Dodge', 'Dakota Club');
insert into car (id, make, model) values (236, 'Toyota', 'Tercel');
insert into car (id, make, model) values (237, 'Chrysler', 'PT Cruiser');
insert into car (id, make, model) values (238, 'GMC', 'Vandura 2500');
insert into car (id, make, model) values (239, 'Chevrolet', 'Silverado 1500');
insert into car (id, make, model) values (240, 'Dodge', 'Ram 3500');
insert into car (id, make, model) values (241, 'Toyota', 'Avalon');
insert into car (id, make, model) values (242, 'Mitsubishi', 'Expo');
insert into car (id, make, model) values (243, 'Saab', '900');
insert into car (id, make, model) values (244, 'Rolls-Royce', 'Phantom');
insert into car (id, make, model) values (245, 'Subaru', 'Impreza');
insert into car (id, make, model) values (246, 'Ford', 'Econoline E250');
insert into car (id, make, model) values (247, 'BMW', '3 Series');
insert into car (id, make, model) values (248, 'Subaru', 'XT');
insert into car (id, make, model) values (249, 'Dodge', 'Viper');
insert into car (id, make, model) values (250, 'Ford', 'Econoline E350');
insert into car (id, make, model) values (251, 'Ford', 'Ranger');
insert into car (id, make, model) values (252, 'Volvo', '850');
insert into car (id, make, model) values (253, 'Jeep', 'Grand Cherokee');
insert into car (id, make, model) values (254, 'Ford', 'F150');
insert into car (id, make, model) values (255, 'Chrysler', 'PT Cruiser');
insert into car (id, make, model) values (256, 'Mitsubishi', 'Tredia');
insert into car (id, make, model) values (257, 'Nissan', 'Sentra');
insert into car (id, make, model) values (258, 'Toyota', 'Xtra');
insert into car (id, make, model) values (259, 'Dodge', 'Challenger');
insert into car (id, make, model) values (260, 'Pontiac', 'Firefly');
insert into car (id, make, model) values (261, 'Dodge', 'D150 Club');
insert into car (id, make, model) values (262, 'Honda', 'del Sol');
insert into car (id, make, model) values (263, 'Ford', 'Mustang');
insert into car (id, make, model) values (264, 'BMW', '6 Series');
insert into car (id, make, model) values (265, 'Kia', 'Optima');
insert into car (id, make, model) values (266, 'Mercury', 'Grand Marquis');
insert into car (id, make, model) values (267, 'BMW', '7 Series');
insert into car (id, make, model) values (268, 'Volkswagen', 'GTI');
insert into car (id, make, model) values (269, 'Nissan', '240SX');
insert into car (id, make, model) values (270, 'Morgan', 'Aero 8');
insert into car (id, make, model) values (271, 'Dodge', 'Challenger');
insert into car (id, make, model) values (272, 'Mazda', 'Mazda3');
insert into car (id, make, model) values (273, 'MINI', 'Cooper');
insert into car (id, make, model) values (274, 'Cadillac', 'Escalade EXT');
insert into car (id, make, model) values (275, 'GMC', 'Sonoma Club');
insert into car (id, make, model) values (276, 'Toyota', 'Land Cruiser');
insert into car (id, make, model) values (277, 'Volkswagen', 'Type 2');
insert into car (id, make, model) values (278, 'Acura', 'Legend');
insert into car (id, make, model) values (279, 'Ford', 'F250');
insert into car (id, make, model) values (280, 'Maybach', '62');
insert into car (id, make, model) values (281, 'Saab', '9-3');
insert into car (id, make, model) values (282, 'Ford', 'Aerostar');
insert into car (id, make, model) values (283, 'Citroën', 'CX');
insert into car (id, make, model) values (284, 'Oldsmobile', 'Intrigue');
insert into car (id, make, model) values (285, 'Geo', 'Prizm');
insert into car (id, make, model) values (286, 'Dodge', 'Ram 3500 Club');
insert into car (id, make, model) values (287, 'Buick', 'Regal');
insert into car (id, make, model) values (288, 'Nissan', 'Altima');
insert into car (id, make, model) values (289, 'Ford', 'Mustang');
insert into car (id, make, model) values (290, 'Kia', 'Rio');
insert into car (id, make, model) values (291, 'Plymouth', 'Horizon');
insert into car (id, make, model) values (292, 'Aptera', 'Typ-1');
insert into car (id, make, model) values (293, 'Mercury', 'Lynx');
insert into car (id, make, model) values (294, 'Mitsubishi', 'Precis');
insert into car (id, make, model) values (295, 'Ford', 'Expedition EL');
insert into car (id, make, model) values (296, 'Pontiac', 'Grand Am');
insert into car (id, make, model) values (297, 'Dodge', 'Dakota');
insert into car (id, make, model) values (298, 'Hyundai', 'Scoupe');
insert into car (id, make, model) values (299, 'Chevrolet', 'Avalanche 1500');
insert into car (id, make, model) values (300, 'Toyota', 'Venza');
insert into car (id, make, model) values (301, 'Volvo', 'V70');
insert into car (id, make, model) values (302, 'Cadillac', 'Fleetwood');
insert into car (id, make, model) values (303, 'GMC', 'Sonoma');
insert into car (id, make, model) values (304, 'Ford', 'Flex');
insert into car (id, make, model) values (305, 'Lotus', 'Esprit');
insert into car (id, make, model) values (306, 'Ford', 'Crown Victoria');
insert into car (id, make, model) values (307, 'Nissan', 'Maxima');
insert into car (id, make, model) values (308, 'Ford', 'Explorer Sport');
insert into car (id, make, model) values (309, 'Chevrolet', 'Corvette');
insert into car (id, make, model) values (310, 'Pontiac', 'Vibe');
insert into car (id, make, model) values (311, 'Mazda', '626');
insert into car (id, make, model) values (312, 'Audi', 'Coupe GT');
insert into car (id, make, model) values (313, 'Mazda', '929');
insert into car (id, make, model) values (314, 'Ford', 'Escape');
insert into car (id, make, model) values (315, 'Chevrolet', 'Malibu');
insert into car (id, make, model) values (316, 'Chevrolet', 'Camaro');
insert into car (id, make, model) values (317, 'Mitsubishi', 'Mighty Max Macro');
insert into car (id, make, model) values (318, 'Oldsmobile', 'Aurora');
insert into car (id, make, model) values (319, 'Oldsmobile', 'Regency');
insert into car (id, make, model) values (320, 'Volkswagen', 'Routan');
insert into car (id, make, model) values (321, 'BMW', 'Alpina B7');
insert into car (id, make, model) values (322, 'Pontiac', 'GTO');
insert into car (id, make, model) values (323, 'Mercedes-Benz', 'C-Class');
insert into car (id, make, model) values (324, 'Porsche', 'Boxster');
insert into car (id, make, model) values (325, 'Ford', 'Escort');
insert into car (id, make, model) values (326, 'Lamborghini', 'Gallardo');
insert into car (id, make, model) values (327, 'Ford', 'Bronco II');
insert into car (id, make, model) values (328, 'Chrysler', 'Town & Country');
insert into car (id, make, model) values (329, 'Jaguar', 'XK');
insert into car (id, make, model) values (330, 'Pontiac', 'Montana');
insert into car (id, make, model) values (331, 'Volkswagen', 'Jetta');
insert into car (id, make, model) values (332, 'Toyota', 'Camry');
insert into car (id, make, model) values (333, 'Subaru', 'Loyale');
insert into car (id, make, model) values (334, 'Infiniti', 'J');
insert into car (id, make, model) values (335, 'Mazda', 'B2600');
insert into car (id, make, model) values (336, 'Toyota', 'Corolla');
insert into car (id, make, model) values (337, 'Suzuki', 'Daewoo Lacetti');
insert into car (id, make, model) values (338, 'Mitsubishi', 'Chariot');
insert into car (id, make, model) values (339, 'Honda', 'Civic');
insert into car (id, make, model) values (340, 'Cadillac', 'Escalade ESV');
insert into car (id, make, model) values (341, 'Mazda', 'Millenia');
insert into car (id, make, model) values (342, 'Mitsubishi', 'Starion');
insert into car (id, make, model) values (343, 'Lexus', 'RX');
insert into car (id, make, model) values (344, 'Lexus', 'LX');
insert into car (id, make, model) values (345, 'Lexus', 'LX');
insert into car (id, make, model) values (346, 'Dodge', 'Charger');
insert into car (id, make, model) values (347, 'GMC', 'Yukon XL 2500');
insert into car (id, make, model) values (348, 'Chrysler', 'Sebring');
insert into car (id, make, model) values (349, 'Plymouth', 'Colt');
insert into car (id, make, model) values (350, 'Daewoo', 'Leganza');
insert into car (id, make, model) values (351, 'Mazda', 'B-Series Plus');
insert into car (id, make, model) values (352, 'GMC', 'Yukon');
insert into car (id, make, model) values (353, 'Mitsubishi', 'Montero');
insert into car (id, make, model) values (354, 'Lincoln', 'Town Car');
insert into car (id, make, model) values (355, 'Jeep', 'Grand Cherokee');
insert into car (id, make, model) values (356, 'Volkswagen', 'Scirocco');
insert into car (id, make, model) values (357, 'Honda', 'Civic');
insert into car (id, make, model) values (358, 'Ford', 'Ranger');
insert into car (id, make, model) values (359, 'Nissan', 'NX');
insert into car (id, make, model) values (360, 'Plymouth', 'Grand Voyager');
insert into car (id, make, model) values (361, 'Toyota', 'Sienna');
insert into car (id, make, model) values (362, 'Toyota', 'Tacoma');
insert into car (id, make, model) values (363, 'Subaru', 'Forester');
insert into car (id, make, model) values (364, 'Infiniti', 'Q');
insert into car (id, make, model) values (365, 'Mazda', '929');
insert into car (id, make, model) values (366, 'Dodge', 'Ram 1500 Club');
insert into car (id, make, model) values (367, 'GMC', 'Rally Wagon G3500');
insert into car (id, make, model) values (368, 'Lexus', 'GS');
insert into car (id, make, model) values (369, 'Toyota', 'Camry Hybrid');
insert into car (id, make, model) values (370, 'Mazda', 'B-Series');
insert into car (id, make, model) values (371, 'Acura', 'RL');
insert into car (id, make, model) values (372, 'Chevrolet', 'Impala');
insert into car (id, make, model) values (373, 'Mitsubishi', 'Pajero');
insert into car (id, make, model) values (374, 'Ford', 'E250');
insert into car (id, make, model) values (375, 'Toyota', 'Matrix');
insert into car (id, make, model) values (376, 'Maybach', 'Landaulet');
insert into car (id, make, model) values (377, 'Mitsubishi', 'Endeavor');
insert into car (id, make, model) values (378, 'Ford', 'E-Series');
insert into car (id, make, model) values (379, 'Mercedes-Benz', 'S-Class');
insert into car (id, make, model) values (380, 'Land Rover', 'Defender');
insert into car (id, make, model) values (381, 'Dodge', 'Grand Caravan');
insert into car (id, make, model) values (382, 'Ford', 'F-Series');
insert into car (id, make, model) values (383, 'Infiniti', 'I');
insert into car (id, make, model) values (384, 'Dodge', 'Viper');
insert into car (id, make, model) values (385, 'Cadillac', 'Eldorado');
insert into car (id, make, model) values (386, 'Aston Martin', 'Rapide');
insert into car (id, make, model) values (387, 'Volkswagen', 'Touareg 2');
insert into car (id, make, model) values (388, 'Toyota', 'Prius');
insert into car (id, make, model) values (389, 'Porsche', 'Cayman');
insert into car (id, make, model) values (390, 'Suzuki', 'Grand Vitara');
insert into car (id, make, model) values (391, 'Suzuki', 'Esteem');
insert into car (id, make, model) values (392, 'Mercury', 'Mountaineer');
insert into car (id, make, model) values (393, 'Ford', 'Crown Victoria');
insert into car (id, make, model) values (394, 'Chevrolet', 'Avalanche 2500');
insert into car (id, make, model) values (395, 'Subaru', 'Legacy');
insert into car (id, make, model) values (396, 'Mazda', 'RX-8');
insert into car (id, make, model) values (397, 'GMC', 'Yukon XL 2500');
insert into car (id, make, model) values (398, 'Chevrolet', 'Corvette');
insert into car (id, make, model) values (399, 'Hyundai', 'Sonata');
insert into car (id, make, model) values (400, 'Toyota', 'Venza');
insert into car (id, make, model) values (401, 'Plymouth', 'Laser');
insert into car (id, make, model) values (402, 'Tesla', 'Roadster');
insert into car (id, make, model) values (403, 'Bentley', 'Continental GTC');
insert into car (id, make, model) values (404, 'Jaguar', 'XJ Series');
insert into car (id, make, model) values (405, 'Spyker', 'C8 Spyder');
insert into car (id, make, model) values (406, 'Cadillac', 'Escalade ESV');
insert into car (id, make, model) values (407, 'Mercedes-Benz', 'SL-Class');
insert into car (id, make, model) values (408, 'Dodge', 'Ram 1500');
insert into car (id, make, model) values (409, 'GMC', 'Envoy');
insert into car (id, make, model) values (410, 'Cadillac', 'Escalade');
insert into car (id, make, model) values (411, 'Maybach', '62');
insert into car (id, make, model) values (412, 'Plymouth', 'Breeze');
insert into car (id, make, model) values (413, 'Lotus', 'Exige');
insert into car (id, make, model) values (414, 'Volvo', 'V90');
insert into car (id, make, model) values (415, 'Mercedes-Benz', 'SLK-Class');
insert into car (id, make, model) values (416, 'Chevrolet', 'TrailBlazer');
insert into car (id, make, model) values (417, 'Chevrolet', 'Cobalt');
insert into car (id, make, model) values (418, 'Chevrolet', 'Silverado 2500');
insert into car (id, make, model) values (419, 'Suzuki', 'Swift');
insert into car (id, make, model) values (420, 'Nissan', 'Titan');
insert into car (id, make, model) values (421, 'Dodge', 'Grand Caravan');
insert into car (id, make, model) values (422, 'Ford', 'ZX2');
insert into car (id, make, model) values (423, 'Mercury', 'Grand Marquis');
insert into car (id, make, model) values (424, 'Subaru', 'Impreza');
insert into car (id, make, model) values (425, 'Lincoln', 'Navigator L');
insert into car (id, make, model) values (426, 'Pontiac', 'Bonneville');
insert into car (id, make, model) values (427, 'Dodge', 'Dakota Club');
insert into car (id, make, model) values (428, 'GMC', 'Envoy');
insert into car (id, make, model) values (429, 'GMC', 'Sierra 1500');
insert into car (id, make, model) values (430, 'Scion', 'tC');
insert into car (id, make, model) values (431, 'Lexus', 'IS F');
insert into car (id, make, model) values (432, 'Buick', 'Riviera');
insert into car (id, make, model) values (433, 'Porsche', 'Boxster');
insert into car (id, make, model) values (434, 'Ford', 'F150');
insert into car (id, make, model) values (435, 'Porsche', '911');
insert into car (id, make, model) values (436, 'Chevrolet', 'Aveo');
insert into car (id, make, model) values (437, 'Dodge', 'Ram Wagon B350');
insert into car (id, make, model) values (438, 'Ford', 'Tempo');
insert into car (id, make, model) values (439, 'Mitsubishi', 'Pajero');
insert into car (id, make, model) values (440, 'Chevrolet', 'Blazer');
insert into car (id, make, model) values (441, 'Mazda', 'MX-5');
insert into car (id, make, model) values (442, 'Pontiac', 'Grand Am');
insert into car (id, make, model) values (443, 'Mazda', 'Mazda6');
insert into car (id, make, model) values (444, 'Bentley', 'Arnage');
insert into car (id, make, model) values (445, 'BMW', '7 Series');
insert into car (id, make, model) values (446, 'Oldsmobile', 'Cutlass Supreme');
insert into car (id, make, model) values (447, 'Acura', 'Integra');
insert into car (id, make, model) values (448, 'Toyota', 'Land Cruiser');
insert into car (id, make, model) values (449, 'Lamborghini', 'Diablo');
insert into car (id, make, model) values (450, 'Mitsubishi', 'Lancer');
insert into car (id, make, model) values (451, 'BMW', 'X3');
insert into car (id, make, model) values (452, 'Ferrari', '612 Scaglietti');
insert into car (id, make, model) values (453, 'Ford', 'F150');
insert into car (id, make, model) values (454, 'Ford', 'Contour');
insert into car (id, make, model) values (455, 'Hyundai', 'Tiburon');
insert into car (id, make, model) values (456, 'Alfa Romeo', '164');
insert into car (id, make, model) values (457, 'Kia', 'Sorento');
insert into car (id, make, model) values (458, 'Ford', 'Flex');
insert into car (id, make, model) values (459, 'Ford', 'F150');
insert into car (id, make, model) values (460, 'Volkswagen', 'Eurovan');
insert into car (id, make, model) values (461, 'Kia', 'Rondo');
insert into car (id, make, model) values (462, 'Dodge', 'Neon');
insert into car (id, make, model) values (463, 'Mazda', 'B2600');
insert into car (id, make, model) values (464, 'Aston Martin', 'Virage');
insert into car (id, make, model) values (465, 'Honda', 'Element');
insert into car (id, make, model) values (466, 'Mercury', 'Cougar');
insert into car (id, make, model) values (467, 'Hummer', 'H3T');
insert into car (id, make, model) values (468, 'Mercedes-Benz', '300TE');
insert into car (id, make, model) values (469, 'Cadillac', 'Eldorado');
insert into car (id, make, model) values (470, 'Audi', 'R8');
insert into car (id, make, model) values (471, 'Mercedes-Benz', 'C-Class');
insert into car (id, make, model) values (472, 'GMC', 'Terrain');
insert into car (id, make, model) values (473, 'Pontiac', 'Montana');
insert into car (id, make, model) values (474, 'Cadillac', 'SRX');
insert into car (id, make, model) values (475, 'Dodge', 'Ram Wagon B350');
insert into car (id, make, model) values (476, 'Mazda', 'B-Series');
insert into car (id, make, model) values (477, 'Plymouth', 'Prowler');
insert into car (id, make, model) values (478, 'Plymouth', 'Grand Voyager');
insert into car (id, make, model) values (479, 'Audi', 'A5');
insert into car (id, make, model) values (480, 'Chevrolet', 'Silverado 3500');
insert into car (id, make, model) values (481, 'Land Rover', 'Freelander');
insert into car (id, make, model) values (482, 'Suzuki', 'SJ');
insert into car (id, make, model) values (483, 'Jeep', 'Patriot');
insert into car (id, make, model) values (484, 'Mercedes-Benz', 'Sprinter 2500');
insert into car (id, make, model) values (485, 'Chrysler', 'Grand Voyager');
insert into car (id, make, model) values (486, 'Mercedes-Benz', 'SL-Class');
insert into car (id, make, model) values (487, 'Lamborghini', 'Murciélago');
insert into car (id, make, model) values (488, 'Mercedes-Benz', 'R-Class');
insert into car (id, make, model) values (489, 'Pontiac', '6000');
insert into car (id, make, model) values (490, 'Chevrolet', 'Tahoe');
insert into car (id, make, model) values (491, 'GMC', 'Safari');
insert into car (id, make, model) values (492, 'Lincoln', 'Town Car');
insert into car (id, make, model) values (493, 'BMW', '745');
insert into car (id, make, model) values (494, 'BMW', '7 Series');
insert into car (id, make, model) values (495, 'Chevrolet', 'Express 2500');
insert into car (id, make, model) values (496, 'Lexus', 'IS');
insert into car (id, make, model) values (497, 'Infiniti', 'M');
insert into car (id, make, model) values (498, 'Honda', 'CR-V');
insert into car (id, make, model) values (499, 'Mitsubishi', 'Outlander');
insert into car (id, make, model) values (500, 'Kia', 'Sportage');
insert into car (id, make, model) values (501, 'Honda', 'Civic');
insert into car (id, make, model) values (502, 'Nissan', 'Maxima');
insert into car (id, make, model) values (503, 'Chrysler', '300');
insert into car (id, make, model) values (504, 'Ford', 'F350');
insert into car (id, make, model) values (505, 'Infiniti', 'I');
insert into car (id, make, model) values (506, 'Cadillac', 'Escalade ESV');
insert into car (id, make, model) values (507, 'Ford', 'F150');
insert into car (id, make, model) values (508, 'Dodge', 'Ram 2500');
insert into car (id, make, model) values (509, 'Pontiac', 'Solstice');
insert into car (id, make, model) values (510, 'Oldsmobile', 'Silhouette');
insert into car (id, make, model) values (511, 'Dodge', 'Spirit');
insert into car (id, make, model) values (512, 'Mercury', 'Mariner');
insert into car (id, make, model) values (513, 'Lexus', 'SC');
insert into car (id, make, model) values (514, 'Lexus', 'CT');
insert into car (id, make, model) values (515, 'Porsche', 'Cayman');
insert into car (id, make, model) values (516, 'Volvo', 'C70');
insert into car (id, make, model) values (517, 'Mercury', 'Topaz');
insert into car (id, make, model) values (518, 'Chevrolet', 'Corvette');
insert into car (id, make, model) values (519, 'Dodge', 'D250 Club');
insert into car (id, make, model) values (520, 'Volvo', 'S70');
insert into car (id, make, model) values (521, 'Audi', 'A6');
insert into car (id, make, model) values (522, 'Eagle', 'Talon');
insert into car (id, make, model) values (523, 'Suzuki', 'Kizashi');
insert into car (id, make, model) values (524, 'Lotus', 'Elise');
insert into car (id, make, model) values (525, 'Ford', 'Mustang');
insert into car (id, make, model) values (526, 'Nissan', 'Quest');
insert into car (id, make, model) values (527, 'Fairthorpe', 'Rockette');
insert into car (id, make, model) values (528, 'Hyundai', 'Tucson');
insert into car (id, make, model) values (529, 'Subaru', 'Outback');
insert into car (id, make, model) values (530, 'Hyundai', 'Accent');
insert into car (id, make, model) values (531, 'Toyota', 'Tacoma');
insert into car (id, make, model) values (532, 'BMW', 'Z4');
insert into car (id, make, model) values (533, 'GMC', 'Canyon');
insert into car (id, make, model) values (534, 'MINI', 'Cooper');
insert into car (id, make, model) values (535, 'Audi', 'Q5');
insert into car (id, make, model) values (536, 'Chrysler', 'Sebring');
insert into car (id, make, model) values (537, 'Pontiac', 'Grand Prix');
insert into car (id, make, model) values (538, 'Nissan', 'Rogue');
insert into car (id, make, model) values (539, 'GMC', 'Sierra');
insert into car (id, make, model) values (540, 'Lexus', 'LX');
insert into car (id, make, model) values (541, 'Jeep', 'Liberty');
insert into car (id, make, model) values (542, 'Dodge', 'Neon');
insert into car (id, make, model) values (543, 'Ford', 'Ranger');
insert into car (id, make, model) values (544, 'Chevrolet', 'Suburban 2500');
insert into car (id, make, model) values (545, 'Chevrolet', 'Cobalt');
insert into car (id, make, model) values (546, 'Mitsubishi', 'Raider');
insert into car (id, make, model) values (547, 'Hyundai', 'Sonata');
insert into car (id, make, model) values (548, 'Kia', 'Soul');
insert into car (id, make, model) values (549, 'Ford', 'F-Series');
insert into car (id, make, model) values (550, 'Mazda', 'RX-7');
insert into car (id, make, model) values (551, 'Lincoln', 'Continental');
insert into car (id, make, model) values (552, 'Jeep', 'Liberty');
insert into car (id, make, model) values (553, 'Porsche', 'Panamera');
insert into car (id, make, model) values (554, 'Cadillac', 'STS');
insert into car (id, make, model) values (555, 'Nissan', 'Titan');
insert into car (id, make, model) values (556, 'Toyota', 'TundraMax');
insert into car (id, make, model) values (557, 'Lexus', 'IS F');
insert into car (id, make, model) values (558, 'GMC', 'Rally Wagon 3500');
insert into car (id, make, model) values (559, 'Mitsubishi', 'Chariot');
insert into car (id, make, model) values (560, 'Toyota', 'T100');
insert into car (id, make, model) values (561, 'Audi', 'S4');
insert into car (id, make, model) values (562, 'GMC', 'Envoy XUV');
insert into car (id, make, model) values (563, 'Jeep', 'Wrangler');
insert into car (id, make, model) values (564, 'Cadillac', 'DeVille');
insert into car (id, make, model) values (565, 'Audi', 'A6');
insert into car (id, make, model) values (566, 'Mitsubishi', 'Endeavor');
insert into car (id, make, model) values (567, 'Dodge', 'Colt');
insert into car (id, make, model) values (568, 'Ford', 'Bronco');
insert into car (id, make, model) values (569, 'Hyundai', 'Genesis');
insert into car (id, make, model) values (570, 'Porsche', 'Cayenne');
insert into car (id, make, model) values (571, 'Isuzu', 'Rodeo');
insert into car (id, make, model) values (572, 'BMW', '8 Series');
insert into car (id, make, model) values (573, 'Hyundai', 'Azera');
insert into car (id, make, model) values (574, 'Toyota', 'Land Cruiser');
insert into car (id, make, model) values (575, 'Mercedes-Benz', '300SE');
insert into car (id, make, model) values (576, 'GMC', 'Jimmy');
insert into car (id, make, model) values (577, 'Lotus', 'Elise');
insert into car (id, make, model) values (578, 'Volvo', 'S40');
insert into car (id, make, model) values (579, 'Dodge', 'Durango');
insert into car (id, make, model) values (580, 'Oldsmobile', 'Intrigue');
insert into car (id, make, model) values (581, 'Ford', 'Bronco II');
insert into car (id, make, model) values (582, 'Dodge', 'Viper RT/10');
insert into car (id, make, model) values (583, 'Ford', 'Ranger');
insert into car (id, make, model) values (584, 'Saab', '900');
insert into car (id, make, model) values (585, 'Jeep', 'Liberty');
insert into car (id, make, model) values (586, 'Mitsubishi', 'Lancer');
insert into car (id, make, model) values (587, 'Buick', 'Regal');
insert into car (id, make, model) values (588, 'Eagle', 'Talon');
insert into car (id, make, model) values (589, 'Isuzu', 'Rodeo');
insert into car (id, make, model) values (590, 'Chevrolet', 'Lumina');
insert into car (id, make, model) values (591, 'Mazda', 'CX-9');
insert into car (id, make, model) values (592, 'Ford', 'E-Series');
insert into car (id, make, model) values (593, 'Volvo', 'XC60');
insert into car (id, make, model) values (594, 'Chevrolet', 'Corvette');
insert into car (id, make, model) values (595, 'Saturn', 'Astra');
insert into car (id, make, model) values (596, 'Lotus', 'Evora');
insert into car (id, make, model) values (597, 'Buick', 'Century');
insert into car (id, make, model) values (598, 'Mitsubishi', 'Truck');
insert into car (id, make, model) values (599, 'Cadillac', 'SRX');
insert into car (id, make, model) values (600, 'Saturn', 'S-Series');
insert into car (id, make, model) values (601, 'Ford', 'E-Series');
insert into car (id, make, model) values (602, 'Ford', 'Econoline E150');
insert into car (id, make, model) values (603, 'Mitsubishi', 'Galant');
insert into car (id, make, model) values (604, 'Oldsmobile', 'Achieva');
insert into car (id, make, model) values (605, 'Mercedes-Benz', 'C-Class');
insert into car (id, make, model) values (606, 'Chevrolet', 'Express 3500');
insert into car (id, make, model) values (607, 'Ford', 'F-Series');
insert into car (id, make, model) values (608, 'Bentley', 'Continental GTC');
insert into car (id, make, model) values (609, 'Hyundai', 'Sonata');
insert into car (id, make, model) values (610, 'GMC', 'Suburban 1500');
insert into car (id, make, model) values (611, 'Chevrolet', 'Express 3500');
insert into car (id, make, model) values (612, 'Mercedes-Benz', '500SEC');
insert into car (id, make, model) values (613, 'Mercury', 'Monterey');
insert into car (id, make, model) values (614, 'Chevrolet', 'Suburban 2500');
insert into car (id, make, model) values (615, 'Lexus', 'RX');
insert into car (id, make, model) values (616, 'Mercedes-Benz', 'E-Class');
insert into car (id, make, model) values (617, 'Volkswagen', 'Jetta');
insert into car (id, make, model) values (618, 'Mazda', 'Mazdaspeed 3');
insert into car (id, make, model) values (619, 'Mazda', 'Mazda5');
insert into car (id, make, model) values (620, 'Lotus', 'Esprit');
insert into car (id, make, model) values (621, 'Ford', 'E-Series');
insert into car (id, make, model) values (622, 'Volkswagen', 'GTI');
insert into car (id, make, model) values (623, 'Ford', 'Mustang');
insert into car (id, make, model) values (624, 'Audi', 'RS6');
insert into car (id, make, model) values (625, 'Toyota', 'Camry');
insert into car (id, make, model) values (626, 'Mercedes-Benz', '600SEL');
insert into car (id, make, model) values (627, 'Lotus', 'Elan');
insert into car (id, make, model) values (628, 'Mitsubishi', 'Tredia');
insert into car (id, make, model) values (629, 'BMW', '5 Series');
insert into car (id, make, model) values (630, 'Ford', 'F150');
insert into car (id, make, model) values (631, 'GMC', 'Vandura 3500');
insert into car (id, make, model) values (632, 'Subaru', 'Tribeca');
insert into car (id, make, model) values (633, 'Volkswagen', 'GTI');
insert into car (id, make, model) values (634, 'Oldsmobile', 'Alero');
insert into car (id, make, model) values (635, 'Oldsmobile', '88');
insert into car (id, make, model) values (636, 'Jeep', 'Grand Cherokee');
insert into car (id, make, model) values (637, 'Mitsubishi', 'Montero Sport');
insert into car (id, make, model) values (638, 'Volkswagen', 'rio');
insert into car (id, make, model) values (639, 'Chrysler', '300');
insert into car (id, make, model) values (640, 'Dodge', 'Ram 1500 Club');
insert into car (id, make, model) values (641, 'Dodge', 'Durango');
insert into car (id, make, model) values (642, 'Scion', 'tC');
insert into car (id, make, model) values (643, 'Ford', 'Tempo');
insert into car (id, make, model) values (644, 'Cadillac', 'Escalade EXT');
insert into car (id, make, model) values (645, 'Isuzu', 'Ascender');
insert into car (id, make, model) values (646, 'Jeep', 'Grand Cherokee');
insert into car (id, make, model) values (647, 'Chevrolet', 'Cobalt');
insert into car (id, make, model) values (648, 'GMC', 'Yukon');
insert into car (id, make, model) values (649, 'Toyota', 'Land Cruiser');
insert into car (id, make, model) values (650, 'Lexus', 'LX');
insert into car (id, make, model) values (651, 'Ford', 'Galaxie');
insert into car (id, make, model) values (652, 'Dodge', 'Avenger');
insert into car (id, make, model) values (653, 'Ford', 'Focus');
insert into car (id, make, model) values (654, 'Nissan', 'Armada');
insert into car (id, make, model) values (655, 'Lexus', 'IS F');
insert into car (id, make, model) values (656, 'Dodge', 'Ram 2500');
insert into car (id, make, model) values (657, 'Dodge', 'Intrepid');
insert into car (id, make, model) values (658, 'Mercury', 'Marauder');
insert into car (id, make, model) values (659, 'Honda', 'S2000');
insert into car (id, make, model) values (660, 'Kia', 'Borrego');
insert into car (id, make, model) values (661, 'MINI', 'Cooper');
insert into car (id, make, model) values (662, 'Oldsmobile', 'Cutlass Supreme');
insert into car (id, make, model) values (663, 'Chrysler', '200');
insert into car (id, make, model) values (664, 'Kia', 'Rondo');
insert into car (id, make, model) values (665, 'Nissan', 'JUKE');
insert into car (id, make, model) values (666, 'Chevrolet', 'Silverado');
insert into car (id, make, model) values (667, 'Volkswagen', 'GTI');
insert into car (id, make, model) values (668, 'Mitsubishi', 'Cordia');
insert into car (id, make, model) values (669, 'Mercedes-Benz', 'SL-Class');
insert into car (id, make, model) values (670, 'Toyota', 'T100 Xtra');
insert into car (id, make, model) values (671, 'Subaru', 'Impreza');
insert into car (id, make, model) values (672, 'Dodge', 'Nitro');
insert into car (id, make, model) values (673, 'Honda', 'Accord');
insert into car (id, make, model) values (674, 'Buick', 'Rendezvous');
insert into car (id, make, model) values (675, 'Chevrolet', 'Impala');
insert into car (id, make, model) values (676, 'Subaru', 'SVX');
insert into car (id, make, model) values (677, 'Toyota', 'Yaris');
insert into car (id, make, model) values (678, 'Volkswagen', 'Golf');
insert into car (id, make, model) values (679, 'GMC', 'Savana 1500');
insert into car (id, make, model) values (680, 'Jaguar', 'XJ');
insert into car (id, make, model) values (681, 'Geo', 'Metro');
insert into car (id, make, model) values (682, 'Suzuki', 'Sidekick');
insert into car (id, make, model) values (683, 'GMC', 'Suburban 2500');
insert into car (id, make, model) values (684, 'GMC', 'Envoy');
insert into car (id, make, model) values (685, 'Mazda', 'RX-7');
insert into car (id, make, model) values (686, 'Mercury', 'Cougar');
insert into car (id, make, model) values (687, 'Ford', 'Aerostar');
insert into car (id, make, model) values (688, 'Dodge', 'Stratus');
insert into car (id, make, model) values (689, 'Volkswagen', 'GLI');
insert into car (id, make, model) values (690, 'Oldsmobile', 'Aurora');
insert into car (id, make, model) values (691, 'Audi', 'A4');
insert into car (id, make, model) values (692, 'Subaru', 'SVX');
insert into car (id, make, model) values (693, 'Bentley', 'Azure');
insert into car (id, make, model) values (694, 'Honda', 'Pilot');
insert into car (id, make, model) values (695, 'Subaru', 'Impreza');
insert into car (id, make, model) values (696, 'Subaru', 'Forester');
insert into car (id, make, model) values (697, 'BMW', '6 Series');
insert into car (id, make, model) values (698, 'BMW', 'M3');
insert into car (id, make, model) values (699, 'Chevrolet', 'Avalanche');
insert into car (id, make, model) values (700, 'Toyota', 'Avalon');
insert into car (id, make, model) values (701, 'GMC', 'Savana 3500');
insert into car (id, make, model) values (702, 'Hyundai', 'Accent');
insert into car (id, make, model) values (703, 'Infiniti', 'FX');
insert into car (id, make, model) values (704, 'Pontiac', 'Grand Prix');
insert into car (id, make, model) values (705, 'Kia', 'Sportage');
insert into car (id, make, model) values (706, 'GMC', 'Savana 3500');
insert into car (id, make, model) values (707, 'GMC', 'Sierra 1500');
insert into car (id, make, model) values (708, 'Volvo', 'XC60');
insert into car (id, make, model) values (709, 'Suzuki', 'Swift');
insert into car (id, make, model) values (710, 'Toyota', 'Venza');
insert into car (id, make, model) values (711, 'Kia', 'Sorento');
insert into car (id, make, model) values (712, 'Pontiac', 'Bonneville');
insert into car (id, make, model) values (713, 'Kia', 'Sportage');
insert into car (id, make, model) values (714, 'Mazda', 'Millenia');
insert into car (id, make, model) values (715, 'GMC', 'Yukon XL 1500');
insert into car (id, make, model) values (716, 'Ford', 'F-Series');
insert into car (id, make, model) values (717, 'Mitsubishi', 'Galant');
insert into car (id, make, model) values (718, 'Mercedes-Benz', 'M-Class');
insert into car (id, make, model) values (719, 'Chrysler', 'Town & Country');
insert into car (id, make, model) values (720, 'Nissan', 'Frontier');
insert into car (id, make, model) values (721, 'Audi', 'R8');
insert into car (id, make, model) values (722, 'GMC', 'Envoy XL');
insert into car (id, make, model) values (723, 'Mitsubishi', 'Lancer Evolution');
insert into car (id, make, model) values (724, 'Toyota', 'Camry Hybrid');
insert into car (id, make, model) values (725, 'Lexus', 'GX');
insert into car (id, make, model) values (726, 'Jeep', 'Compass');
insert into car (id, make, model) values (727, 'Jaguar', 'XJ');
insert into car (id, make, model) values (728, 'Volkswagen', 'CC');
insert into car (id, make, model) values (729, 'Toyota', 'Camry');
insert into car (id, make, model) values (730, 'Dodge', 'Dakota');
insert into car (id, make, model) values (731, 'BMW', '3 Series');
insert into car (id, make, model) values (732, 'Mercedes-Benz', 'S-Class');
insert into car (id, make, model) values (733, 'Acura', 'RL');
insert into car (id, make, model) values (734, 'Ford', 'Thunderbird');
insert into car (id, make, model) values (735, 'Chrysler', 'Voyager');
insert into car (id, make, model) values (736, 'GMC', '3500');
insert into car (id, make, model) values (737, 'Nissan', 'Maxima');
insert into car (id, make, model) values (738, 'Suzuki', 'Grand Vitara');
insert into car (id, make, model) values (739, 'Pontiac', 'G6');
insert into car (id, make, model) values (740, 'Chevrolet', 'Corvette');
insert into car (id, make, model) values (741, 'BMW', '3 Series');
insert into car (id, make, model) values (742, 'Chevrolet', 'Classic');
insert into car (id, make, model) values (743, 'Ford', 'Taurus');
insert into car (id, make, model) values (744, 'Pontiac', 'Montana');
insert into car (id, make, model) values (745, 'GMC', 'Yukon');
insert into car (id, make, model) values (746, 'Audi', 'TT');
insert into car (id, make, model) values (747, 'Mitsubishi', 'Galant');
insert into car (id, make, model) values (748, 'Volkswagen', 'GTI');
insert into car (id, make, model) values (749, 'Oldsmobile', 'Achieva');
insert into car (id, make, model) values (750, 'Cadillac', 'Catera');
insert into car (id, make, model) values (751, 'Dodge', 'Intrepid');
insert into car (id, make, model) values (752, 'Ford', 'Tempo');
insert into car (id, make, model) values (753, 'Cadillac', 'CTS');
insert into car (id, make, model) values (754, 'Mazda', 'B-Series Plus');
insert into car (id, make, model) values (755, 'Mitsubishi', 'Lancer');
insert into car (id, make, model) values (756, 'Toyota', 'Tacoma Xtra');
insert into car (id, make, model) values (757, 'Dodge', 'Sprinter');
insert into car (id, make, model) values (758, 'Volkswagen', 'Eurovan');
insert into car (id, make, model) values (759, 'Ford', 'Taurus');
insert into car (id, make, model) values (760, 'Lexus', 'LS');
insert into car (id, make, model) values (761, 'Volvo', 'S40');
insert into car (id, make, model) values (762, 'Chevrolet', 'Silverado 3500');
insert into car (id, make, model) values (763, 'Mercury', 'Sable');
insert into car (id, make, model) values (764, 'Aston Martin', 'DB9');
insert into car (id, make, model) values (765, 'Chevrolet', 'Equinox');
insert into car (id, make, model) values (766, 'Toyota', 'Highlander');
insert into car (id, make, model) values (767, 'Geo', 'Metro');
insert into car (id, make, model) values (768, 'Acura', 'SLX');
insert into car (id, make, model) values (769, 'Aston Martin', 'V8 Vantage');
insert into car (id, make, model) values (770, 'Subaru', 'Impreza');
insert into car (id, make, model) values (771, 'Mitsubishi', 'GTO');
insert into car (id, make, model) values (772, 'Toyota', '4Runner');
insert into car (id, make, model) values (773, 'Kia', 'Spectra');
insert into car (id, make, model) values (774, 'Chevrolet', 'Express 1500');
insert into car (id, make, model) values (775, 'GMC', 'Canyon');
insert into car (id, make, model) values (776, 'Mazda', 'Miata MX-5');
insert into car (id, make, model) values (777, 'Mercedes-Benz', 'CL-Class');
insert into car (id, make, model) values (778, 'Mercedes-Benz', 'E-Class');
insert into car (id, make, model) values (779, 'Dodge', 'Ram 1500');
insert into car (id, make, model) values (780, 'Dodge', 'Ram Van 1500');
insert into car (id, make, model) values (781, 'Ford', 'Windstar');
insert into car (id, make, model) values (782, 'Ford', 'F250');
insert into car (id, make, model) values (783, 'Mercedes-Benz', 'C-Class');
insert into car (id, make, model) values (784, 'BMW', 'M3');
insert into car (id, make, model) values (785, 'Pontiac', 'Bonneville');
insert into car (id, make, model) values (786, 'Buick', 'Regal');
insert into car (id, make, model) values (787, 'Volkswagen', 'Fox');
insert into car (id, make, model) values (788, 'Maybach', 'Landaulet');
insert into car (id, make, model) values (789, 'Subaru', 'Baja');
insert into car (id, make, model) values (790, 'Lexus', 'IS');
insert into car (id, make, model) values (791, 'Volkswagen', 'Passat');
insert into car (id, make, model) values (792, 'Acura', 'NSX');
insert into car (id, make, model) values (793, 'Honda', 'Odyssey');
insert into car (id, make, model) values (794, 'Ford', 'Thunderbird');
insert into car (id, make, model) values (795, 'Honda', 'Odyssey');
insert into car (id, make, model) values (796, 'Hyundai', 'Tiburon');
insert into car (id, make, model) values (797, 'Ford', 'F150');
insert into car (id, make, model) values (798, 'Buick', 'Regal');
insert into car (id, make, model) values (799, 'Lincoln', 'Navigator');
insert into car (id, make, model) values (800, 'Chevrolet', 'Corvette');
insert into car (id, make, model) values (801, 'Nissan', 'Altima');
insert into car (id, make, model) values (802, 'Mercedes-Benz', 'SLK-Class');
insert into car (id, make, model) values (803, 'Toyota', 'Land Cruiser');
insert into car (id, make, model) values (804, 'Mazda', 'MPV');
insert into car (id, make, model) values (805, 'Nissan', '200SX');
insert into car (id, make, model) values (806, 'Ford', 'Mustang');
insert into car (id, make, model) values (807, 'Audi', 'riolet');
insert into car (id, make, model) values (808, 'Mercedes-Benz', 'SL-Class');
insert into car (id, make, model) values (809, 'Mitsubishi', 'Mirage');
insert into car (id, make, model) values (810, 'Chevrolet', 'Equinox');
insert into car (id, make, model) values (811, 'Acura', 'RL');
insert into car (id, make, model) values (812, 'Mitsubishi', 'Mighty Max');
insert into car (id, make, model) values (813, 'Ford', 'Expedition');
insert into car (id, make, model) values (814, 'Toyota', 'Avalon');
insert into car (id, make, model) values (815, 'Ford', 'Thunderbird');
insert into car (id, make, model) values (816, 'Ford', 'Five Hundred');
insert into car (id, make, model) values (817, 'Toyota', 'Tacoma');
insert into car (id, make, model) values (818, 'Mercury', 'Mariner');
insert into car (id, make, model) values (819, 'BMW', 'M3');
insert into car (id, make, model) values (820, 'Jeep', 'Liberty');
insert into car (id, make, model) values (821, 'Ford', 'F150');
insert into car (id, make, model) values (822, 'Infiniti', 'Q');
insert into car (id, make, model) values (823, 'Mercedes-Benz', 'C-Class');
insert into car (id, make, model) values (824, 'Mercury', 'Grand Marquis');
insert into car (id, make, model) values (825, 'Infiniti', 'G35');
insert into car (id, make, model) values (826, 'Lincoln', 'MKZ');
insert into car (id, make, model) values (827, 'Chevrolet', 'Express 3500');
insert into car (id, make, model) values (828, 'Saab', '9-3');
insert into car (id, make, model) values (829, 'McLaren', 'MP4-12C');
insert into car (id, make, model) values (830, 'Chevrolet', 'Sportvan G30');
insert into car (id, make, model) values (831, 'Chevrolet', 'G-Series G20');
insert into car (id, make, model) values (832, 'Chevrolet', 'Suburban 1500');
insert into car (id, make, model) values (833, 'Volkswagen', 'rio');
insert into car (id, make, model) values (834, 'Dodge', 'Dakota Club');
insert into car (id, make, model) values (835, 'Mitsubishi', 'L300');
insert into car (id, make, model) values (836, 'Honda', 'Prelude');
insert into car (id, make, model) values (837, 'Chevrolet', 'Malibu Maxx');
insert into car (id, make, model) values (838, 'Audi', 'S5');
insert into car (id, make, model) values (839, 'Toyota', 'Yaris');
insert into car (id, make, model) values (840, 'Saturn', 'Astra');
insert into car (id, make, model) values (841, 'Chevrolet', 'Suburban 1500');
insert into car (id, make, model) values (842, 'Kia', 'Rio');
insert into car (id, make, model) values (843, 'Lexus', 'GS');
insert into car (id, make, model) values (844, 'Plymouth', 'Laser');
insert into car (id, make, model) values (845, 'Ford', 'Fusion');
insert into car (id, make, model) values (846, 'Audi', 'A4');
insert into car (id, make, model) values (847, 'Volkswagen', 'Jetta');
insert into car (id, make, model) values (848, 'Ford', 'Model T');
insert into car (id, make, model) values (849, 'Mercury', 'Grand Marquis');
insert into car (id, make, model) values (850, 'Toyota', 'Celica');
insert into car (id, make, model) values (851, 'Toyota', '4Runner');
insert into car (id, make, model) values (852, 'Ford', 'F350');
insert into car (id, make, model) values (853, 'Chevrolet', 'Tracker');
insert into car (id, make, model) values (854, 'Chevrolet', 'Tahoe');
insert into car (id, make, model) values (855, 'Bentley', 'Continental GTC');
insert into car (id, make, model) values (856, 'Subaru', 'Brat');
insert into car (id, make, model) values (857, 'Ford', 'Club Wagon');
insert into car (id, make, model) values (858, 'Ford', 'Mustang');
insert into car (id, make, model) values (859, 'Mitsubishi', 'Endeavor');
insert into car (id, make, model) values (860, 'Subaru', 'Forester');
insert into car (id, make, model) values (861, 'Audi', '5000S');
insert into car (id, make, model) values (862, 'Acura', 'TSX');
insert into car (id, make, model) values (863, 'Toyota', 'Camry');
insert into car (id, make, model) values (864, 'Kia', 'Rio5');
insert into car (id, make, model) values (865, 'GMC', 'Savana 1500');
insert into car (id, make, model) values (866, 'Mercedes-Benz', 'C-Class');
insert into car (id, make, model) values (867, 'Kia', 'Rio');
insert into car (id, make, model) values (868, 'Ford', 'Edge');
insert into car (id, make, model) values (869, 'Ford', 'Taurus');
insert into car (id, make, model) values (870, 'Mitsubishi', 'Diamante');
insert into car (id, make, model) values (871, 'Mercedes-Benz', 'SL-Class');
insert into car (id, make, model) values (872, 'Porsche', 'Cayenne');
insert into car (id, make, model) values (873, 'Ford', 'Ranger');
insert into car (id, make, model) values (874, 'Nissan', 'Altima');
insert into car (id, make, model) values (875, 'Chevrolet', 'Corvette');
insert into car (id, make, model) values (876, 'Honda', 'Odyssey');
insert into car (id, make, model) values (877, 'Dodge', 'Dakota Club');
insert into car (id, make, model) values (878, 'Plymouth', 'Colt');
insert into car (id, make, model) values (879, 'Pontiac', 'Grand Prix');
insert into car (id, make, model) values (880, 'Land Rover', 'Defender 110');
insert into car (id, make, model) values (881, 'Nissan', '370Z');
insert into car (id, make, model) values (882, 'Lexus', 'RX');
insert into car (id, make, model) values (883, 'Audi', '100');
insert into car (id, make, model) values (884, 'Honda', 'Accord');
insert into car (id, make, model) values (885, 'Toyota', 'Tundra');
insert into car (id, make, model) values (886, 'Pontiac', 'Grand Prix');
insert into car (id, make, model) values (887, 'Lincoln', 'Town Car');
insert into car (id, make, model) values (888, 'Dodge', 'Dakota');
insert into car (id, make, model) values (889, 'Ford', 'Thunderbird');
insert into car (id, make, model) values (890, 'Mercedes-Benz', 'Sprinter 2500');
insert into car (id, make, model) values (891, 'Subaru', 'Leone');
insert into car (id, make, model) values (892, 'Dodge', 'Stealth');
insert into car (id, make, model) values (893, 'Pontiac', 'Bonneville');
insert into car (id, make, model) values (894, 'Jaguar', 'X-Type');
insert into car (id, make, model) values (895, 'Oldsmobile', 'Aurora');
insert into car (id, make, model) values (896, 'Lexus', 'RX');
insert into car (id, make, model) values (897, 'Buick', 'LaCrosse');
insert into car (id, make, model) values (898, 'Mercury', 'Grand Marquis');
insert into car (id, make, model) values (899, 'Mazda', 'B-Series');
insert into car (id, make, model) values (900, 'Plymouth', 'Breeze');
insert into car (id, make, model) values (901, 'Isuzu', 'Stylus');
insert into car (id, make, model) values (902, 'Acura', 'MDX');
insert into car (id, make, model) values (903, 'Mitsubishi', 'Raider');
insert into car (id, make, model) values (904, 'Pontiac', 'Trans Sport');
insert into car (id, make, model) values (905, 'Subaru', 'Legacy');
insert into car (id, make, model) values (906, 'BMW', '7 Series');
insert into car (id, make, model) values (907, 'Toyota', 'Tercel');
insert into car (id, make, model) values (908, 'Mercury', 'Mariner');
insert into car (id, make, model) values (909, 'Hummer', 'H1');
insert into car (id, make, model) values (910, 'Lexus', 'LX');
insert into car (id, make, model) values (911, 'Mercedes-Benz', 'C-Class');
insert into car (id, make, model) values (912, 'Land Rover', 'Range Rover');
insert into car (id, make, model) values (913, 'Ford', 'Expedition');
insert into car (id, make, model) values (914, 'Ford', 'Expedition EL');
insert into car (id, make, model) values (915, 'Ford', 'Crown Victoria');
insert into car (id, make, model) values (916, 'Mazda', 'Millenia');
insert into car (id, make, model) values (917, 'Chevrolet', 'Monte Carlo');
insert into car (id, make, model) values (918, 'Oldsmobile', 'Regency');
insert into car (id, make, model) values (919, 'Ford', 'Mustang');
insert into car (id, make, model) values (920, 'Dodge', 'Ram');
insert into car (id, make, model) values (921, 'Maybach', '62');
insert into car (id, make, model) values (922, 'Chrysler', 'Town & Country');
insert into car (id, make, model) values (923, 'Audi', 'R8');
insert into car (id, make, model) values (924, 'Pontiac', 'Grand Am');
insert into car (id, make, model) values (925, 'Oldsmobile', '98');
insert into car (id, make, model) values (926, 'Nissan', 'Pathfinder');
insert into car (id, make, model) values (927, 'Audi', 'A6');
insert into car (id, make, model) values (928, 'Lexus', 'SC');
insert into car (id, make, model) values (929, 'Honda', 'Accord');
insert into car (id, make, model) values (930, 'Land Rover', 'LR3');
insert into car (id, make, model) values (931, 'Mitsubishi', 'Eclipse');
insert into car (id, make, model) values (932, 'Toyota', 'Land Cruiser');
insert into car (id, make, model) values (933, 'GMC', '1500');
insert into car (id, make, model) values (934, 'Chevrolet', 'Corvette');
insert into car (id, make, model) values (935, 'Jeep', 'Liberty');
insert into car (id, make, model) values (936, 'Lexus', 'LX');
insert into car (id, make, model) values (937, 'Subaru', 'Forester');
insert into car (id, make, model) values (938, 'Pontiac', 'Sunbird');
insert into car (id, make, model) values (939, 'Mercury', 'Sable');
insert into car (id, make, model) values (940, 'Buick', 'Special');
insert into car (id, make, model) values (941, 'Maybach', '57');
insert into car (id, make, model) values (942, 'Cadillac', 'Fleetwood');
insert into car (id, make, model) values (943, 'Lexus', 'GS');
insert into car (id, make, model) values (944, 'Dodge', 'Ram 3500');
insert into car (id, make, model) values (945, 'Ford', 'Fiesta');
insert into car (id, make, model) values (946, 'Volkswagen', 'Jetta');
insert into car (id, make, model) values (947, 'GMC', 'Savana 3500');
insert into car (id, make, model) values (948, 'Honda', 'Passport');
insert into car (id, make, model) values (949, 'GMC', 'Envoy XL');
insert into car (id, make, model) values (950, 'Nissan', 'Cube');
insert into car (id, make, model) values (951, 'Pontiac', 'Gemini');
insert into car (id, make, model) values (952, 'Cadillac', 'STS');
insert into car (id, make, model) values (953, 'Mercedes-Benz', 'R-Class');
insert into car (id, make, model) values (954, 'Nissan', 'Maxima');
insert into car (id, make, model) values (955, 'Mazda', '626');
insert into car (id, make, model) values (956, 'Volvo', 'C70');
insert into car (id, make, model) values (957, 'Toyota', 'Xtra');
insert into car (id, make, model) values (958, 'Ford', 'Taurus');
insert into car (id, make, model) values (959, 'Volvo', 'S60');
insert into car (id, make, model) values (960, 'Jaguar', 'S-Type');
insert into car (id, make, model) values (961, 'Toyota', 'Paseo');
insert into car (id, make, model) values (962, 'Mitsubishi', 'Mirage');
insert into car (id, make, model) values (963, 'Suzuki', 'SJ');
insert into car (id, make, model) values (964, 'Mercury', 'Mountaineer');
insert into car (id, make, model) values (965, 'Suzuki', 'XL7');
insert into car (id, make, model) values (966, 'Lexus', 'LX');
insert into car (id, make, model) values (967, 'Chevrolet', 'G-Series 3500');
insert into car (id, make, model) values (968, 'Volkswagen', 'Golf');
insert into car (id, make, model) values (969, 'Ford', 'Mustang');
insert into car (id, make, model) values (970, 'Mazda', 'B-Series Plus');
insert into car (id, make, model) values (971, 'Mercedes-Benz', 'C-Class');
insert into car (id, make, model) values (972, 'Toyota', 'Highlander');
insert into car (id, make, model) values (973, 'Ford', 'LTD');
insert into car (id, make, model) values (974, 'Dodge', 'Ram 50');
insert into car (id, make, model) values (975, 'Bentley', 'Continental GTC');
insert into car (id, make, model) values (976, 'Lotus', 'Esprit');
insert into car (id, make, model) values (977, 'Mercedes-Benz', 'CLS-Class');
insert into car (id, make, model) values (978, 'Subaru', 'Forester');
insert into car (id, make, model) values (979, 'Buick', 'Skylark');
insert into car (id, make, model) values (980, 'Buick', 'Roadmaster');
insert into car (id, make, model) values (981, 'Saab', '900');
insert into car (id, make, model) values (982, 'Chevrolet', 'Camaro');
insert into car (id, make, model) values (983, 'Mercury', 'Grand Marquis');
insert into car (id, make, model) values (984, 'Ford', 'EXP');
insert into car (id, make, model) values (985, 'Volkswagen', 'Fox');
insert into car (id, make, model) values (986, 'Cadillac', 'Escalade');
insert into car (id, make, model) values (987, 'Chevrolet', 'Express 3500');
insert into car (id, make, model) values (988, 'Chevrolet', 'Astro');
insert into car (id, make, model) values (989, 'Dodge', 'Ram 1500 Club');
insert into car (id, make, model) values (990, 'Porsche', '911');
insert into car (id, make, model) values (991, 'Mercedes-Benz', 'S-Class');
insert into car (id, make, model) values (992, 'Saab', '900');
insert into car (id, make, model) values (993, 'Mitsubishi', 'Mirage');
insert into car (id, make, model) values (994, 'Pontiac', 'Firebird');
insert into car (id, make, model) values (995, 'Mitsubishi', 'Diamante');
insert into car (id, make, model) values (996, 'Mitsubishi', 'Eclipse');
insert into car (id, make, model) values (997, 'Volkswagen', 'Golf');
insert into car (id, make, model) values (998, 'Mercedes-Benz', 'SL-Class');
insert into car (id, make, model) values (999, 'Dodge', 'Ram 3500');
insert into car (id, make, model) values (1000, 'Ford', 'F150');

