server:
  port: 8303

spring:
  application:
    name: zuul-service

zuul:
  ignoredServices: '*'
  ignoredPatterns: /**/toBeIgnored/**
  prefix: /api
  routes:
    h2-db-service:
      path: /database/**
      service-id: h2-db-service
      sensitiveHeaders:
      # stripPrefix: false #swithes off given zuul prefix (if given) eg. /api - see config above
      # url: http://localhost:8301/ in case that service-id is unknown or not registered in eureka server
    rest-client:
      path: /rest/**
      service-id: rest-client
      # url: http://localhost:8302/ in case that service-id is unknown or not registered in eureka server
    #legacy: /**

#ribbon:
#  eureka:
#    enabled: false

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#use camellCase, not snake-case


